<?php
function wooaioie_get_fields() {
    return array(
        'id' => 'ID',
        'type' => 'Type',
        'sku' => 'SKU',
        'name' => 'Name',
        'published' => 'Published',
        'featured' => '"Is featured?"',
        'catalog_visibility' => '"Visibility in catalog"',
        'short_description' => '"Short description"',
        'description' => 'Description',
        'date_on_sale_from' => '"Date sale price starts"',
        'date_on_sale_to' => '"Date sale price ends"',
        'tax_status' => '"Tax status"',
        'tax_class' => '"Tax class"',
        'stock_status' => '"In stock?"',
        'stock' => 'Stock',
        'backorders_allowed' => '"Backorders allowed?"',
        'sold_individually' => '"Sold individually?"',
        'weight_lbs' => '"Weight (lbs)"',
        'length_in' => '"Length (in)"',
        'width_in' => '"Width (in)"',
        'height_in' => '"Height (in)"',
        'allow_customer_reviews' => '"Allow customer reviews?"',
        'purchase_note' => '"Purchase note"',
        'sale_price' => '"Sale price"',
        'regular_price' => '"Regular price"',
        'categories' => 'Categories',
        'tags' => 'Tags',
        'shipping_class' => '"Shipping class"',
        'images' => 'Images',
        'download_limit' => '"Download limit"',
        'download_expiry_days' => '"Download expiry days"',
        'parent' => 'Parent',
        'grouped_products' => '"Grouped products"',
        'upsells' => 'Upsells',
        'cross-sells' => 'Cross-sells',
        'external_url' => '"External URL"',
        'button_text' => '"Button text"',
        'position' => 'Position',
        'attribute_1_name' => '"Attribute 1 name"',
        'attribute_1_values' => '"Attribute 1 value(s)"',
        'attribute_1_visible' => '"Attribute 1 visible"',
        'attribute_1_global' => '"Attribute 1 global"',
        'attribute_2_name' => '"Attribute 2 name"',
        'attribute_2_values' => '"Attribute 2 value(s)"',
        'attribute_2_visible' => '"Attribute 2 visible"',
        'attribute_2_global' => '"Attribute 2 global"',
        'meta_wpcom_is_markdown' => '"Meta: _wpcom_is_markdown"',
        'download_1_name' => '"Download 1 name"',
        'download_1_url' => '"Download 1 URL"',
        'download_2_name' => '"Download 2 name"',
        'download_2_url' => '"Download 2 URL"',
    );
}